### ISSUE TITLE
Crash Nitro Kart freezing after Intro Cutscene (July Prototype Build)

### ISSUE THREAD

**Issue by Darkaiser0** [xemu-project/xemu#1297]
### Title

https://xemu.app/titles/5655001f/#Crash-Nitro-Kart

### Bug Description

This build of the game (Jul 29 2003) always crashes after the FMV intro cutscene (black screen).

Note: It requires 128 MB RAM to play.

### Expected Behavior

Should be playable.

### xemu Version

Version:      0.7.71
Branch:       master
Commit:       22db3304a454b2d289a9d5ea488fa3c3dec836f4
Date:         Tue Oct 11 18:38:37 UTC 2022

### System Information

OS:  Windows 10
CPU:          AMD Ryzen 5 5600G with Radeon Graphics      
GPU:    AMD Radeon(TM) Graphics

**Comment by ShadowLuigi** [comment]
The prototype has issues with video files, as well as audio file playback issues in relation to audio files that don't loop.

**Comment by OrganicOstrich** [comment]
0.adad.0 has reported that the issue has been resolved with the current build 0.7.127

**Comment by ShadowLuigi** [comment]
Tried the July 2003 prototype again, though I'm still having the same issue where the prototype freezes after the intro cutscene.

**Comment by Darkaiser0** [comment]
> 0.adad.0 has reported that the issue has been resolved with the current build 0.7.127

This does not seem to be true at all, it has exactly the same issue as before, freezing after the intro cutscene. Tested on the latest version.

**Comment by Adad-G** [comment]
> > 0.adad.0 has reported that the issue has been resolved with the current build 0.7.127
> 
> This does not seem to be true at all, it has exactly the same issue as before, freezing after the intro cutscene. Tested on the latest version.

Sorry, it was my mistake not knowing about the existence of that prototype. Although to be honest I don't know how relevant it is since it's an unofficial game and it's not even on the compatibility page. Have you tested if it works on the Vulkan branch?
Could you, @OrganicOstrich, please reopen it?
