### ISSUE TITLE
Star Wars Battlefront 2 split screen purple static/artifact issue

### ISSUE THREAD

**Issue by Doctor98Who** [xemu-project/xemu#1949]
### Title

https://xemu.app/titles/4c41001a/#Star-Wars-Battlefront-II

### Bug Description

For Star Wars battlefront 2 when playing split screen, any map that renders the open sky gives an awful purple texture for P2-P4. Makes it really difficult to play and figured it could be something to look at! Thanks so much for the hard work!

### Expected Behavior

Expected to have all split screen players render the sky same as p1

### xemu Version

0.8.2

**Comment by Doctor98Who** [comment]
![Image](https://github.com/user-attachments/assets/dfd6d328-fdab-4753-8cf3-5ddccd89bfb1)

**Comment by jyetcv** [comment]
I get different lines on vulkan, plus the fog effect tied to player 2's view.

https://github.com/user-attachments/assets/22ba2df5-5e17-4788-a51a-624ad2a8dfea

https://github.com/user-attachments/assets/52b31b23-cbfa-4361-960f-7604dae6520a

**Comment by mborgerson** [comment]
Please retest

**Comment by jyetcv** [comment]
Looks fixed now:

https://github.com/user-attachments/assets/bfc706d4-2d5c-417f-9331-4c685419a73b

**Comment by mborgerson** [comment]
Thanks @jyetcv

**Comment by Doctor98Who** [comment]
The issue still persists for me. P2-P4 have the weird purple texture as seen in photo!

**Comment by jyetcv** [comment]
@Doctor98Who
What is the name of the GPU you are using?
Are your GPU drivers up to date?
Which version of xemu are you using?

**Comment by Doctor98Who** [comment]
Nvidia 1070 . Drivers up to date and used the most recent version- 0.8.36

**Comment by re4thewin** [comment]
> Nvidia 1070 . Drivers up to date and used the most recent version- 0.8.36


Version 0.8.39 (Mar 17, 2025)
is the latest please update xemu and retest
