### ISSUE TITLE
Game: Otogi 1&2, Issue: water shader zigzagging and not displaying proper on left side and left and top side of screen theres black&green banding artifacts/ground and shadow rendering issues

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [xemu-project/xemu#2179]
### Titles

Otogi FS-002 [46530002]

https://xemu.app/titles/46530002/

Otogi: Hyakki Toubatsu Emaki FS-004 [46530004]

https://xemu.app/titles/46530004/

### Bug Description

Issues with otogi1 and 2
The water harshly zigzags instead of proper distortion also displays red/blue/green/white left side instead of reflective silver like the waterfalls do and black banding left and top in otogi2, meshes/ground textures seem to stretch but also flickering object shadows like from bridges occur in otogi1 and black/green banding artifacting left and top.

Otogi1:

1. launch game
2. select level: a clouded moon,
3. move camera while going through level with character water harshly zigzags instead of proper distortion and meshes/ground textures seem to stretch/distort but also flickering object shadows like from bridges occur and left and top screen side has weird green/ black banding artifacts 

![Image](https://github.com/user-attachments/assets/3cf8d879-bb19-4ba0-b8ab-a725d0c855a0)
![Image](https://github.com/user-attachments/assets/77d2e48f-fa55-49a8-9577-bc18288e2499)

Otogi2:

1. launch game
2. select level: any level with water, example : forest of havoc, then scroll to a quiet moon
3. Go to water and you see 
left screen side ,water is in red/blue/green/white stripes. And has weird black banding left and top.

![Image](https://github.com/user-attachments/assets/d1e1e928-ab7a-4d0c-b628-ddda41795afa)

![Image](https://github.com/user-attachments/assets/b8332f11-1a82-4f17-b82a-a642471f2ccf)

### Expected Behavior

Otogi1:
water should be properly distorted ,meshes/ground textures shouldn't stretch/distort but also object shadows like bridges shouldnt be flickering / changing shapes and no green/black banding artifacts left and top.

Otogi2:
Water should be properly distorted without being seperated into base colors of red/blue/green/white , should be actually reflective silver shaded on left side of screen and no black banding left and top.

### xemu Version

All versions, tested on Version: v0.8.62
Branch: master
Date: May 15, 2025

### System Information

CPU:i9-13900K @5.5 ghz
Graphics Device: Nvidia Geforce RTX 4090
Graphics Driver: NVIDIA 576.40
OS Platform: Windows
OS Version: 11

### Additional Context

Here's a showcase video:

https://youtube.com/watch?v=TH2GMZpkhjQ

**Comment by Triticum0** [comment]
Retest should be fixed at 1x

**Comment by washingleavesandthensome23-434** [comment]
> Retest should be fixed at 1x

Fixed for both otogi1 and otogi2?

In Version 0.8.66?

**Comment by washingleavesandthensome23-434** [comment]
> Retest should be fixed at 1x

So nope even Version 0.8.66 @1x its bugged , still get the left and top black artifact banding and the water in otogi2 on left side of screen turned from red/blue/green/white to yellow/black , also one more black banding artifact is on character shadows,  see in youtube clip I previously posted @13:00-13:12

![Image](https://github.com/user-attachments/assets/e23a1475-7b50-4563-967d-a3c81293dd99)
![Image](https://github.com/user-attachments/assets/f4182204-74bf-4990-bf1e-edfc9136dac4)
![Image](https://github.com/user-attachments/assets/c13017d1-35d1-4ed3-adc0-aba054e7d293)

**Comment by washingleavesandthensome23-434** [comment]
Also 1 more issue still persists for both games and its this

https://github.com/xemu-project/xemu/issues/1869

It's gotten alot better but you still notice it for example still some in Otogi2, as well, when there’s spoken word on top of fire effects, as can  be heard in the video I posted still not 100% fixed

**Comment by Triticum0** [comment]
I tested Otogi 1 and couldn't reproduce the issues at 1x are you using widescreen patch?

**Comment by Triticum0** [comment]
Doing so more testing, the issue with upscaling not really noticeable at 1x at higher resolution it cause issue otogi 2 I getting that pattern in water but not yellow color like op it same color as the water so hard to notice.

**Comment by Triticum0** [comment]
Here a renderdoc for post processing effect for otogi 2
https://drive.google.com/file/d/1DdVvU9QKLgcDzzFcMKEk_QGYCBZSVs-m/view?usp=sharing

Trace

[otogi 2 post processing banding trace.zip](https://github.com/user-attachments/files/22447595/otogi.2.post.processing.banding.trace.zip)

**Comment by Triticum0** [comment]
Seems to occur on hardware.
