### ISSUE TITLE
[Bug] Halo 2 Missing Skybox?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [xemu-project/xemu#229]
https://xemu.app/titles/4d530064/#Halo-2

`In Halo 2 on The Armory level, the skybox and/or the earth does not appear.`
![capture_071_04032021_033118](https://user-images.githubusercontent.com/6149596/109940673-55bd1a00-7ca0-11eb-9450-849683bd7ea9.jpg)

**Comment by TheAwesome98-Real** [comment]
happens on most/all multiplayer maps. may be due to fog because on some maps you can see the clouds if you look straight up

**Comment by Triticum0** [comment]
@TheAwesome98-Real retest should be fixed

**Comment by TheAwesome98-Real** [comment]
> @TheAwesome98-Real retest should be fixed

will do in a few hours. i get xemu from nixpkgs so i'll have to update it on there first

**Comment by lostromb** [comment]
This appears fixed as of 0.8.34

![Image](https://github.com/user-attachments/assets/f802920c-25cc-4300-b40c-bdb3a4e70c39)

**Comment by Triticum0** [comment]
Can be closed

**Comment by TheAwesome98-Real** [comment]
not fixed. is this a different issue?

![a screenshot of halo 2 running in xemu 0.8.34. the skybox is not visible—it is just greyish-orange.](https://github.com/user-attachments/assets/e39c2119-d0f6-46de-89c2-704b8c290bdf)

EDIT: thought i might need to erase my shaders folder, but that didn't help

**Comment by Triticum0** [comment]
Thanks, should wait for you to test. Reopen

**Comment by mborgerson** [comment]
> not fixed. is this a different issue?
> 
> ![a screenshot of halo 2 running in xemu 0.8.34. the skybox is not visible—it is just greyish-orange.](https://github.com/user-attachments/assets/e39c2119-d0f6-46de-89c2-704b8c290bdf)
> 
> EDIT: thought i might need to erase my shaders folder, but that didn't help

What hardware, os, and release build are you using @TheAwesome98-Real

**Comment by TheAwesome98-Real** [comment]
> What hardware, os, and release build are you using

gpu: ATI Radeon 5700 XT
cpu: AMD Ryzen 5 2600X
os: NixOS 24.11.714772.11415c7ae853 (Vicuna) (Linux 6.6.79)
not sure what you're asking by release build. the version is 0.8.34. i built it by cloning nixpkgs, modifying the xemu package's version (which automatically causes it to pull the 0.8.34 sources), then running `nix-build -A xemu` and `result/bin/xemu`. this doesn't modify the source in any way (apart from zeroing out the build time for reproducible builds), so it should be functionally equivalent to the regular 0.8.34 release.

**Comment by mborgerson** [comment]
> not sure what you're asking by release build

There are multiple unofficial distributions of xemu for Linux and I haven't audited them so I don't know what or how they are building and who's tried them. You're the first I think I've seen use xemu on NixOS :)

- Can you try the app image?
- What driver are you using?

**Comment by TheAwesome98-Real** [comment]
> * Can you try the app image?

no, it goes `AppRun: GLib: ../../../glib/gmem.c:106: failed to allocate 16382701336644316621 bytes`. i would have said that it was probably to do with using `appimage-run`, but why on earth is it allocating something like 16 billion gigabytes? are there non-appimage releases? i could try running that with `nix-alien` (it runs a program in a way that's compatible with nixos)


> * What driver are you using?

`amdgpu`

**Comment by mborgerson** [comment]
> no, it goes AppRun: GLib: ../../../glib/gmem.c:106: failed to allocate 16382701336644316621 bytes. 

Very weird...

> are there non-appimage releases? 

There are debs that are built on GitHub actions inside the xemu-ubuntu-* artifacts (e.g. https://github.com/xemu-project/xemu/actions/runs/13776634303)

By the way, have you tried both Vulkan and OpenGL renderers?

Also @jyetcv can you reproduce this (Halo 2 Blood Gultch skybox missing) issue on your AMD machine?

**Comment by TheAwesome98-Real** [comment]
> There are debs that are built on GitHub actions inside the xemu-ubuntu-* artifacts

will definitely try these!

> By the way, have you tried both Vulkan and OpenGL renderers?

i actually thought this might be the issue but i couldn't find the setting to change it

**Comment by mborgerson** [comment]
@TheAwesome98-Real 

> i actually thought this might be the issue but i couldn't find the setting to change it

![Image](https://github.com/user-attachments/assets/10b33241-b4e7-4e8c-a5bf-0ab1ef5c414a)

View -> Backend

**Comment by TheAwesome98-Real** [comment]
> View -> Backend

oh, weird, i didn't notice that before. i'll try that

**Comment by jyetcv** [comment]
> Also [@jyetcv](https://github.com/jyetcv) can you reproduce this (Halo 2 Blood Gultch skybox missing) issue on your AMD machine?

Blue skies for me on both OpenGL and Vulkan:

![Image](https://github.com/user-attachments/assets/9371291a-55e4-4995-bc8c-6edf1c1c230d)

**Comment by TheAwesome98-Real** [comment]
> View -> Backend

![xemu screenshot. there is no such option](https://github.com/user-attachments/assets/62d0563f-ff27-47a6-af98-169186660f3f)

**Comment by TheAwesome98-Real** [comment]
also, the ubuntu version (which i got running via `nix-alien` and a hacked together steam runtime) also allocates the 16 billion gigabytes like the appimage does

**Comment by mborgerson** [comment]
Absence of the Backend menu option in your build here indicates to me that you actually have an older version of xemu, despite what the version number says. Note that changing the xemu version file does not actually cause it to download a different version of xemu source for building. The link to xemu source for v0.8.34 is at https://github.com/xemu-project/xemu/releases/download/v0.8.34/src.tar.gz

**Comment by TheAwesome98-Real** [comment]
that's weird, because [that's exactly how nixpkgs downloads the xemu source code to build](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/xe/xemu/package.nix#L35)

i actually think you might be right, though—when i change the hash to the correct one, it fails to build, saying `unknown option --meson=meson`, but if i keep the wrong (old) hash, it successfully builds, making me think it's somehow using the old source code even though it downloads the new one
