### ISSUE TITLE
Halo 2 v1.0: Assertion failed! 

### ISSUE THREAD

**Issue by theboy181** [xemu-project/xemu#288]
https://xemu.app/titles/4d530064/#Halo-2

### Bug Description
Assertion failed! 

Error will occur when you zoom in  looking through glass railing in the first level at the spot shown in the screen capture.
![image](https://user-images.githubusercontent.com/9299743/119065605-c831c200-b992-11eb-9dfb-0341143ecc50.png)

Video
https://user-images.githubusercontent.com/9299743/119066318-607c7680-b994-11eb-86ec-5155c20dc7bb.mp4

Version: 0.5.2-3-g68b8043af9
Last-known Working: Unknown

System Specs
https://valid.x86.fr/r74im1

**Comment by Triticum0** [comment]
This also affect half life 2, Full spectrum Warrior: 10 Hammers and Midnight Club 3: DUB Edition https://github.com/mborgerson/xemu/issues/349.
https://xemu.app/titles/45410091/#Half-Life-2
https://xemu.app/titles/545100f8/#Full-Spectrum-Warrior-Ten-Hammers (I Tested it independently so it is not on compact report)
https://xemu.app/titles/54540079/#Midnight-Club-3-DUB-Edition
https://xemu.app/titles/55530018/#Beyond-Good-Evil
https://xemu.app/titles/5451001a/#Nickelodeon-SpongeBob-SquarePants-in-Battle-for-Bikini-Bottom

**Comment by tmob03** [comment]
Still happens in Half life 2 as of 1/10/21

**Comment by alejandrodf95** [comment]
When i start xemu crash after one minute with this message.

**Comment by Triticum0** [comment]
@w4rexx Can you retest

**Comment by Triticum0** [comment]
@theboy181 Can you retest

**Comment by Triticum0** [comment]
@theboy181 Can you retest the issue been fixed

**Comment by theboy181** [comment]
When was it fixed. It's been a while since I tested this game.

**Comment by Triticum0** [comment]
@theboy181 It was merged 17 days ago #989 and the assertion probably changed

**Comment by theboy181** [comment]
Not tested myself, but have been told the issue has been resolved.

**Comment by antangelo** [comment]
> It was merged 17 days ago #989 and the assertion probably changed

Are you sure this is the same issue? This assert message is very generic as compared to the one in #635 which is what that PR closed.

**Comment by Goonslaper** [comment]
![image_2023-11-05_095246928](https://github.com/xemu-project/xemu/assets/149951979/56272f75-9d60-4450-ac95-932bd7ddd2f8)
Xemu error. tried everything but it still won't work

**Comment by Goonslaper** [comment]
how do you fix it?

**Comment by dracc** [comment]
> ![image_2023-11-05_095246928](https://user-images.githubusercontent.com/149951979/280534888-56272f75-9d60-4450-ac95-932bd7ddd2f8.png) Xemu error. tried everything but it still won't work

That's a different error from what OP reported. Disable DTS/Surround sound in your EEPROM (MsDash settings, typically) and you'll be good to go.
