### ISSUE TITLE
Amped 2 (MS-065 [4d530041]): Some 3D objects misplaced

### ISSUE THREAD

**Issue by RitschiRitsch** [xemu-project/xemu#304]
### Title Information

* Title: Amped 2 (MS-065 [4d530041])
* https://xemu.app/titles/4d530041/#Amped-2

### Bug Description

On "Breckenridge" and "Mount Hood" some 3D objects are misplaced and "hovering" in the sky. Rails, funboxes, logs and buildings are affected. Physically, the objects are correctly placed, which means that you can ride into invisble rails, buildings etc. This issue is kind of game breaking because you cannot complete the game or beat the challenges respectively (unless you exactly know where the relevant objects are physically placed). 

On the first mountain "Millicent", however, the issue is not persistent.

Steps to reproduce this issue:
1. Start a new ride on "Breckenridge" or "Mount Hood"
2. Watch for rails or other objects in the sky and therefore not at their correct place.

![amped_2_glitch_3](https://user-images.githubusercontent.com/59421441/119815725-22c7a280-beec-11eb-9130-a32333a38963.png)

### Expected Behavior

3D objects such as rails, logs, funboxes and buildings are drawn at their correct physical place. See screenshot below (sorry for the bad quality).

![Foto 07 01 22, 21 26 10](https://user-images.githubusercontent.com/59421441/148604247-a88a8b56-0fc0-49ec-bdbf-7b39396413bc.jpg)

### Version

* Version: build-202105250704 (f72f9be)
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 64-bit (21H1)			| 
| CPU			| Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz			| 
| Graphics Device	| NVIDIA GTX 1060 6GB			| 
| Graphics Driver	| NVIDIA Geforce Game Ready Driver 466.27			| 

### Additional Context

None

**Comment by kjettern** [comment]
I think this is fixed as of v0.6.2-51-g3fd15218c7.. The framerate is also very good now! 
The only issue now is that trees are dark and lighting on some maps are not working. Quick fix maybe?

**Comment by RitschiRitsch** [comment]
Not fixed for me. Have you tried Breckenridge? Please post a screenshot of Breckenridge ride.

**Comment by kjettern** [comment]
My mistake! Breckenridge is indeed still broken :(

**Comment by Deerhall** [comment]
I have the same issues on 0.6.2 (-78-g2b27021eef).

Objects in the sky on "Breckenridge" and "Mt. Hood".
Objects invisible (maybe under map?) on "Laax 1".
This bug is only visual, objects has their original collision (so it's possible to grind on the invincible objects).

![image](https://user-images.githubusercontent.com/1902752/155728705-780e19cf-73f4-4c6d-b8a1-a2060a492a11.png)
Picture of Laax 1 where you can see missing cable-way (hard to take pictures of invisible boxes and rails).

**Comment by Alroys** [comment]
Fixed for me on 0.6.6

**Comment by mborgerson** [comment]
@RitschiRitsch can you confirm

**Comment by RitschiRitsch** [comment]
Confirmed working. Issue can be closed. Thanks a lot!
