### ISSUE TITLE
Meta: Shader compilation failures

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#315]
### Title Information
NHL-2002 - https://xemu.app/titles/45410005
<details close>
<summary>Failing Fragment Shader from NHL 2002 OLD </summary>
<br>
#version 330

struct VertexData {
  float inv_w;
  vec4 D0;
  vec4 D1;
  vec4 B0;
  vec4 B1;
  float Fog;
  vec4 T0;
  vec4 T1;
  vec4 T2;
  vec4 T3;
};
noperspective in VertexData g_vtx;
#define vtx g_vtx

out vec4 fragColor;

uniform vec4 fogColor;
float sign1(float x) {
    x *= 255.0;
    return (x-128.0)/127.0;
}
float sign2(float x) {
    x *= 255.0;
    if (x >= 128.0) return (x-255.5)/127.5;
               else return (x+0.5)/127.5;
}
float sign3(float x) {
    x *= 255.0;
    if (x >= 128.0) return (x-256.0)/127.0;
               else return (x)/127.0;
}
float sign3_to_0_to_1(float x) {
    if (x >= 0) return x/2;
           else return 1+x/2;
}
vec3 dotmap_zero_to_one(vec3 col) {
    return col;
}
vec3 dotmap_minus1_to_1_d3d(vec3 col) {
    return vec3(sign1(col.r),sign1(col.g),sign1(col.b));
}
vec3 dotmap_minus1_to_1_gl(vec3 col) {
    return vec3(sign2(col.r),sign2(col.g),sign2(col.b));
}
vec3 dotmap_minus1_to_1(vec3 col) {
    return vec3(sign3(col.r),sign3(col.g),sign3(col.b));
}
vec3 dotmap_hilo_1(vec3 col) {
    return col;
}
vec3 dotmap_hilo_hemisphere_d3d(vec3 col) {
    return col;
}
vec3 dotmap_hilo_hemisphere_gl(vec3 col) {
    return col;
}
vec3 dotmap_hilo_hemisphere(vec3 col) {
    return col;
}
const float[9] gaussian3x3 = float[9](
    1.0/16.0, 2.0/16.0, 1.0/16.0,
    2.0/16.0, 4.0/16.0, 2.0/16.0,
    1.0/16.0, 2.0/16.0, 1.0/16.0);
const vec2[9] convolution3x3 = vec2[9](
    vec2(-1.0,-1.0),vec2(0.0,-1.0),vec2(1.0,-1.0),
    vec2(-1.0, 0.0),vec2(0.0, 0.0),vec2(1.0, 0.0),
    vec2(-1.0, 1.0),vec2(0.0, 1.0),vec2(1.0, 1.0));
vec4 gaussianFilter2DRectProj(sampler2DRect sampler, vec3 texCoord) {
    vec4 sum = vec4(0.0);
    for (int i = 0; i < 9; i++) {
        sum += gaussian3x3[i]*textureProj(sampler,
                   texCoord + vec3(convolution3x3[i], 0.0));
    }
    return sum;
}
uniform ivec4 clipRegion[1];
uniform sampler2D texSamp0;
uniform sampler2D texSamp1;
uniform float alphaRef;
uniform vec4 c0_2;
void main() {
/*  Window-clip (Inclusive) */
bool clipContained = false;
for (int i = 0; i < 1; i++) {
  bvec4 clipTest = bvec4(lessThan(gl_FragCoord.xy, clipRegion[i].xy),
                         greaterThan(gl_FragCoord.xy, clipRegion[i].zw));
  if (!any(clipTest)) {
    clipContained = true;
    break;
  }
}n
if (!clipContained) { discard; }
vec4 pD0 = vtx.D0 / vtx.inv_w;
vec4 pD1 = vtx.D1 / vtx.inv_w;
vec4 pB0 = vtx.B0 / vtx.inv_w;
vec4 pB1 = vtx.B1 / vtx.inv_w;
vec4 pFog = vec4(fogColor.rgb, clamp(vtx.Fog / vtx.inv_w, 0.0, 1.0));
vec4 pT0 = vtx.T0 / vtx.inv_w;
vec4 pT1 = vtx.T1 / vtx.inv_w;
vec4 pT2 = vtx.T2 / vtx.inv_w;
vec4 pT3 = vtx.T3 / vtx.inv_w;

vec4 v0 = pD0;
vec4 v1 = pD1;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
vec4 t1 = textureProj(texSamp1, pT1.xyw);
vec4 t2 = pT2;
vec4 t3 = vec4(0.0); /* PS_TEXTUREMODES_NONE */
vec4 r1;
vec4 r0;
r0.a = t0.a;
// Stage 0
r1.rgb = clamp(vec3(dot((2.0 * max(t2.rgb, 0.0) - 1.0), (2.0 * max(v1.rgb, 0.0) - 1.0))), -1.0, 1.0);
dot(vec4(0.0).rgb, vec4(0.0).rgb).a = dot(vec4(0.0).rgb, vec4(0.0).rgb).b;
r1.a = r1.b;
// Stage 1
r1.rgb = clamp(vec3((max(r1.rgb, 0.0) * max(r1.rgb, 0.0))), -1.0, 1.0);
r1.a = clamp(((max(r1.a, 0.0) * max(r1.a, 0.0))), -1.0, 1.0);
// Stage 2
r0.rgb = clamp(vec3((max(v0.rgb, 0.0) * t0.rgb)), -1.0, 1.0);
t1.rgb = clamp(vec3((t1.rgb * c0_2.rgb)), -1.0, 1.0);
r0.a = clamp(((max(v0.a, 0.0) * t0.a)), -1.0, 1.0);
t1.a = clamp(((t1.a * c0_2.a)), -1.0, 1.0);
// Stage 3
r1.rgb = clamp(vec3((nr1.rgb * r1.rgb)), -1.0, 1.0);
r1.a = clamp(((r1.a * r1.a)), -1.0, 1.0);
// Stage 4
r1.rgb = clamp(vec3((r1.rgb * r1.rgb)), -1.0, 1.0);
r1.a = clamp(((r1.a * r1.a)), -1.0, 1.0);
// Final Combiner
fragColor.rgb = max(vec4(max(r1.rgb, 0.0) * max(t1.rgb, 0.0), 0.0).rgb, 0.0) + mix(vec3(max(r0.rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(t0.a, 0.0);
if (!(fragColor.a > alphaRef)) discard;
}

nv2a: fragment shader compilation failed: Fragment shader failed to compile with the following errors:
ERROR: 0:117: error(#216) Vector field selection out of range "a"
ERROR: 0:117: error(#216) Vector field selection out of range "b"
ERROR: 0:117: error(#164) l-value required: assign (can't modify a const)
ERROR: error(#273) 3 compilation errors.  No code generated

</details>

<details close>
<summary>Failing Fragment Shader from NHL 2002 NEW </summary>
<br>
#version 400

uniform vec2 clipRange;
uniform vec2 surfaceSize;

uniform vec4 c[192];

uniform vec4 fogColor;
uniform float fogParam[2];

#define fogPlane c[0x39]
#define texMat0 mat4(c[0x44], c[0x44+1], c[0x44+2], c[0x44+3])
#define texMat1 mat4(c[0x4c], c[0x4c+1], c[0x4c+2], c[0x4c+3])
#define texMat2 mat4(c[0x54], c[0x54+1], c[0x54+2], c[0x54+3])
#define texMat3 mat4(c[0x5c], c[0x5c+1], c[0x5c+2], c[0x5c+3])

vec4 oPos = vec4(0.0,0.0,0.0,1.0);
vec4 oD0 = vec4(0.0,0.0,0.0,1.0);
vec4 oD1 = vec4(0.0,0.0,0.0,1.0);
vec4 oB0 = vec4(0.0,0.0,0.0,1.0);
vec4 oB1 = vec4(0.0,0.0,0.0,1.0);
vec4 oPts = vec4(0.0,0.0,0.0,1.0);
vec4 oFog = vec4(1.0,0.0,0.0,1.0);
vec4 oT0 = vec4(0.0,0.0,0.0,1.0);
vec4 oT1 = vec4(0.0,0.0,0.0,1.0);
vec4 oT2 = vec4(0.0,0.0,0.0,1.0);
vec4 oT3 = vec4(0.0,0.0,0.0,1.0);

vec4 decompress_11_11_10(int cmp) {
    float x = float(bitfieldExtract(cmp, 0,  11)) / 1023.0;
    float y = float(bitfieldExtract(cmp, 11, 11)) / 1023.0;
    float z = float(bitfieldExtract(cmp, 22, 10)) / 511.0;
    return vec4(x, y, z, 1);
}
struct VertexData {
  float inv_w;
  vec4 D0;
  vec4 D1;
  vec4 B0;
  vec4 B1;
  float Fog;
  vec4 T0;
  vec4 T1;
  vec4 T2;
  vec4 T3;
};
noperspective out VertexData g_vtx;
#define vtx g_vtx

layout(location = 0) in vec4 v0;
layout(location = 1) in vec4 v1;
layout(location = 2) in vec4 v2;
layout(location = 3) in vec4 v3;
layout(location = 4) in vec4 v4;
layout(location = 5) in vec4 v5;
layout(location = 6) in vec4 v6;
layout(location = 7) in vec4 v7;
layout(location = 8) in vec4 v8;
layout(location = 9) in vec4 v9;
layout(location = 10) in vec4 v10;
layout(location = 11) in vec4 v11;
layout(location = 12) in vec4 v12;
layout(location = 13) in vec4 v13;
layout(location = 14) in vec4 v14;
layout(location = 15) in vec4 v15;

int A0 = 0;

vec4 R0 = vec4(0.0,0.0,0.0,0.0);
vec4 R1 = vec4(0.0,0.0,0.0,0.0);
vec4 R2 = vec4(0.0,0.0,0.0,0.0);
vec4 R3 = vec4(0.0,0.0,0.0,0.0);
vec4 R4 = vec4(0.0,0.0,0.0,0.0);
vec4 R5 = vec4(0.0,0.0,0.0,0.0);
vec4 R6 = vec4(0.0,0.0,0.0,0.0);
vec4 R7 = vec4(0.0,0.0,0.0,0.0);
vec4 R8 = vec4(0.0,0.0,0.0,0.0);
vec4 R9 = vec4(0.0,0.0,0.0,0.0);
vec4 R10 = vec4(0.0,0.0,0.0,0.0);
vec4 R11 = vec4(0.0,0.0,0.0,0.0);
#define R12 oPos

vec4 _temp_vec;
int _temp_addr;

/* Converts the input to vec4, pads with last component */
vec4 _in(float v) { return vec4(v); }
vec4 _in(vec2 v) { return v.xyyy; }
vec4 _in(vec3 v) { return v.xyzz; }
vec4 _in(vec4 v) { return v.xyzw; }

#define INFINITY (1.0 / 0.0)

#define MOV(dest, mask, src) dest.mask = _MOV(_in(src)).mask
vec4 _MOV(vec4 src)
{
  return src;
}

#define MUL(dest, mask, src0, src1) dest.mask = _MUL(_in(src0), _in(src1)).mask
vec4 _MUL(vec4 src0, vec4 src1)
{
  return src0 * src1;
}

#define ADD(dest, mask, src0, src1) dest.mask = _ADD(_in(src0), _in(src1)).mask
vec4 _ADD(vec4 src0, vec4 src1)
{
  return src0 + src1;
}

#define MAD(dest, mask, src0, src1, src2) dest.mask = _MAD(_in(src0), _in(src1), _in(src2)).mask
vec4 _MAD(vec4 src0, vec4 src1, vec4 src2)
{
  return src0 * src1 + src2;
}

#define DP3(dest, mask, src0, src1) dest.mask = _DP3(_in(src0), _in(src1)).mask
vec4 _DP3(vec4 src0, vec4 src1)
{
  return vec4(dot(src0.xyz, src1.xyz));
}

#define DPH(dest, mask, src0, src1) dest.mask = _DPH(_in(src0), _in(src1)).mask
vec4 _DPH(vec4 src0, vec4 src1)
{
  return vec4(dot(vec4(src0.xyz, 1.0), src1));
}

#define DP4(dest, mask, src0, src1) dest.mask = _DP4(_in(src0), _in(src1)).mask
vec4 _DP4(vec4 src0, vec4 src1)
{
  return vec4(dot(src0, src1));
}

#define DST(dest, mask, src0, src1) dest.mask = _DST(_in(src0), _in(src1)).mask
vec4 _DST(vec4 src0, vec4 src1)
{
  return vec4(1.0,
              src0.y * src1.y,
              src0.z,
              src1.w);
}

#define MIN(dest, mask, src0, src1) dest.mask = _MIN(_in(src0), _in(src1)).mask
vec4 _MIN(vec4 src0, vec4 src1)
{
  return min(src0, src1);
}

#define MAX(dest, mask, src0, src1) dest.mask = _MAX(_in(src0), _in(src1)).mask
vec4 _MAX(vec4 src0, vec4 src1)
{
  return max(src0, src1);
}

#define SLT(dest, mask, src0, src1) dest.mask = _SLT(_in(src0), _in(src1)).mask
vec4 _SLT(vec4 src0, vec4 src1)
{
  return vec4(lessThan(src0, src1));
}

#define ARL(dest, src) dest = _ARL(_in(src).x)
int _ARL(float src)
{
  /* Xbox GPU does specify rounding, OpenGL doesn't; so we need a bias.
   * Example: We probably want to floor 16.99.. to 17, not 16.
   * Source of error (why we get 16.99.. instead of 17.0) is typically
   * vertex-attributes being normalized from a byte value to float:
   *   17 / 255 = 0.06666.. so is this 0.06667 (ceil) or 0.06666 (floor)?
   * Which value we get depends on the host GPU.
   * If we multiply these rounded values by 255 later, we get:
   *   17.00 (ARL result = 17) or 16.99 (ARL result = 16).
   * We assume the intend was to get 17, so we add our bias to fix it. */
  return int(floor(src + 0.001));
}

#define SGE(dest, mask, src0, src1) dest.mask = _SGE(_in(src0), _in(src1)).mask
vec4 _SGE(vec4 src0, vec4 src1)
{
  return vec4(greaterThanEqual(src0, src1));
}

#define RCP(dest, mask, src) dest.mask = _RCP(_in(src).x).mask
vec4 _RCP(float src)
{
  return vec4(1.0 / src);
}

#define RCC(dest, mask, src) dest.mask = _RCC(_in(src).x).mask
vec4 _RCC(float src)
{
  float t = 1.0 / src;
  if (t > 0.0) {
    t = clamp(t, 5.42101e-020, 1.884467e+019);
  } else {
    t = clamp(t, -1.884467e+019, -5.42101e-020);
  }
  return vec4(t);
}

#define RSQ(dest, mask, src) dest.mask = _RSQ(_in(src).x).mask
vec4 _RSQ(float src)
{
  if (src == 0.0) { return vec4(INFINITY); }
  if (isinf(src)) { return vec4(0.0); }
  return vec4(inversesqrt(abs(src)));
}

#define EXP(dest, mask, src) dest.mask = _EXP(_in(src).x).mask
vec4 _EXP(float src)
{
  vec4 result;
  result.x = exp2(floor(src));
  result.y = src - floor(src);
  result.z = exp2(src);
  result.w = 1.0;
  return result;
}

#define LOG(dest, mask, src) dest.mask = _LOG(_in(src).x).mask
vec4 _LOG(float src)
{
  float tmp = abs(src);
  if (tmp == 0.0) { return vec4(-INFINITY, 1.0f, -INFINITY, 1.0f); }
  vec4 result;
  result.x = floor(log2(tmp));
  result.y = tmp / exp2(floor(log2(tmp)));
  result.z = log2(tmp);
  result.w = 1.0;
  return result;
}

#define LIT(dest, mask, src) dest.mask = _LIT(_in(src)).mask
vec4 _LIT(vec4 src)
{
  vec4 s = src;
  float epsilon = 1.0 / 256.0;
  s.w = clamp(s.w, -(128.0 - epsilon), 128.0 - epsilon);
  s.x = max(s.x, 0.0);
  s.y = max(s.y, 0.0);
  vec4 t = vec4(1.0, 0.0, 0.0, 1.0);
  t.y = s.x;
  t.z = (s.x > 0.0) ? exp2(s.w * log2(s.y)) : 0.0;
  return t;
}
void main() {
  /* Slot 0: 0x00000000 0x002C601B 0x0C36106C 0x2F200FF8 */
  MOV(R2,xyzw, c[99]);

  /* Slot 1: 0x00000000 0x002C201B 0x0C36106C 0x2F300FF8 */
  MOV(R3,xyzw, c[97]);

  /* Slot 2: 0x00000000 0x002C401B 0x0C36106C 0x2F400FF8 */
  MOV(R4,xyzw, c[98]);

  /* Slot 3: 0x00000000 0x006DC01B 0x0C3613FC 0x2F500FF8 */
  ADD(R5,xyzw, c[110], v0.w);

  /* Slot 4: 0x00000000 0x006DA01B 0x0C3613FC 0x2E600FF8 */
  ADD(R6,xyz, c[109], v0.w);

  /* Slot 5: 0x00000000 0x006D801B 0x0C3613FC 0x2C700FF8 */
  ADD(R7,xy, c[108], v0.w);

  /* Slot 6: 0x00000000 0x014E2000 0x0800186C 0x21800FF8 */
  MAX(R8,w, v0.x, c[113].x);

  /* Slot 7: 0x00000000 0x016D6000 0x0DFE106C 0x21900FF8 */
  SLT(R9,w, c[107].x, v0.w);

  /* Slot 8: 0x00000000 0x006D6000 0x0C3617FC 0x20708358 */
  ADD(c107,x, c[107].x, -v0.w);

  /* Slot 9: 0x00000000 0x008FA0FF 0x55FE1AA8 0x38A00FF8 */
  MAD(R10,x, R5.w, c[125].w, c[125].z);

  /* Slot 10: 0x00000000 0x008F4000 0x5436186C 0x9FB00FF8 */
  MAD(R11,xyzw, R5.x, c[122], R2);

  /* Slot 11: 0x00000000 0x008EE000 0x6436186C 0xDF000FF8 */
  MAD(R0,xyzw, R6.x, c[119], R3);

  /* Slot 12: 0x00000000 0x008E8000 0x7436186D 0x1F200FF8 */
  MAD(R2,xyzw, R7.x, c[116], R4);

  /* Slot 13: 0x00000000 0x008F6055 0x5436186E 0xDF300FF8 */
  MAD(R3,xyzw, R5.y, c[123], R11);

  /* Slot 14: 0x00000000 0x008F0055 0x6436186C 0x1F400FF8 */
  MAD(R4,xyzw, R6.y, c[120], R0);

  /* Slot 15: 0x00000000 0x042E60AA 0x0C36106E 0x94840FF8 */
  MOV(_temp_vec,y, c[115].z);
  RCP(R1,y, R10.x);
  R8.y = _temp_vec.y;

  /* Slot 16: 0x00000000 0x008D60FF 0x94AA1800 0x30708358 */
  MAD(c107,x, R9.w, c[107].y, c[107].x);

  /* Slot 17: 0x00000000 0x018D6000 0x0DFE106C 0x28800FF8 */
  SGE(R8,x, c[107].x, v0.w);

  /* Slot 18: 0x00000000 0x008EA055 0x7436186C 0x9F900FF8 */
  MAD(R9,xyzw, R7.y, c[117], R2);

  /* Slot 19: 0x00000000 0x016D6000 0x0DFE106C 0x22800FF8 */
  SLT(R8,z, c[107].x, v0.w);

  /* Slot 20: 0x00000000 0x008F20AA 0x6436186D 0x1FB00FF8 */
  MAD(R11,xyzw, R6.z, c[121], R4);

  /* Slot 21: 0x00000000 0x00400055 0x15FF086C 0x24A00FF8 */
  MUL(R10,y, R1.y, R8.w);

  /* Slot 22: 0x00000000 0x008FA0AA 0x54AA1800 0x32000FF8 */
  MAD(R0,z, R5.z, c[125].y, c[125].x);

  /* Slot 23: 0x00000000 0x006E401B 0x0C36146E 0xDF200FF8 */
  ADD(R2,xyzw, c[114], -R11);

  /* Slot 24: 0x00000000 0x008E2100 0x85FE1800 0x30708388 */
  MAD(c113,x, -R8.x, c[113].w, c[113].x);

  /* Slot 25: 0x00000000 0x008E00AA 0x84001BFC 0x24400FF8 */
  MAD(R4,y, R8.z, c[112].x, v0.w);

  /* Slot 26: 0x00000000 0x008E20AA 0x84AB0800 0x30708388 */
  MAD(c113,x, R8.z, R8.y, c[113].x);

  /* Slot 27: 0x00000000 0x0A4DE0AA 0x84361956 0x9F540FF8 */
  MUL(_temp_vec,xyzw, R8.z, c[111]);
  EXP(R1,y, R10.y);
  R5.xyzw = _temp_vec.xyzw;

  /* Slot 28: 0x00000000 0x00400055 0x1401486C 0x22400FF8 */
  MUL(R4,z, R1.y, R10.x);

  /* Slot 29: 0x00000000 0x008DC055 0x4436186D 0x5F600FF8 */
  MAD(R6,xyzw, R4.y, c[110], R5);

  /* Slot 30: 0x00000000 0x008D8055 0x4436186D 0x5C700FF8 */
  MAD(R7,xy, R4.y, c[108], R5);

  /* Slot 31: 0x00000000 0x008EC0AA 0x4436186E 0x5FA00FF8 */
  MAD(R10,xyzw, R4.z, c[118], R9);

  /* Slot 32: 0x00000000 0x008DA055 0x4436186D 0x5E900FF8 */
  MAD(R9,xyz, R4.y, c[109], R5);

  /* Slot 33: 0x00000000 0x008F80AA 0x4436186C 0xDFB00FF8 */
  MAD(R11,xyzw, R4.z, c[124], R3);

  /* Slot 34: 0x00000000 0x0A00001B 0x08361155 0x90340FF8 */
  EXP(R3,y, R6.y);

  /* Slot 35: 0x00000000 0x0A00001B 0x08361155 0xD0040FF8 */
  EXP(R0,y, R7.y);

  /* Slot 36: 0x00000000 0x0A4D601B 0xB436186D 0x91B04584 */
  MUL(_temp_vec,w, R11, c[107]);
  EXP(c176,y, R6.x);
  R11.w = _temp_vec.w;

  /* Slot 37: 0x00000000 0x0A360055 0x0C3612A9 0x9830458C */
  MOV(_temp_vec,x, c[176].y);
  EXP(c177,y, R6.z);
  R3.x = _temp_vec.x;

  /* Slot 38: 0x00000000 0x0A362055 0x0C3613FD 0x92304594 */
  MOV(_temp_vec,z, c[177].y);
  EXP(c178,y, R6.w);
  R3.z = _temp_vec.z;

  /* Slot 39: 0x00000000 0x0A364055 0x0C36106D 0xD130459C */
  MOV(_temp_vec,w, c[178].y);
  EXP(c179,y, R7.x);
  R3.w = _temp_vec.w;

  /* Slot 40: 0x00000000 0x0A366055 0x0C36106E 0x580045A4 */
  MOV(_temp_vec,x, c[179].y);
  EXP(c180,y, R9.x);
  R0.x = _temp_vec.x;

  /* Slot 41: 0x00000000 0x0A00001B 0x08361156 0x50540FF8 */
  EXP(R5,y, R9.y);

  /* Slot 42: 0x00000000 0x0020001B 0xB436106C 0x2070F818 */
  MOV(oD0,xyzw, R11);

  /* Slot 43: 0x00000000 0x032E20AA 0x4554186C 0x1F60C364 */
  MIN(_temp_vec,xyzw, R4.z, c[113].z);
  MOV(c108,xy, R0);
  R6.xyzw = _temp_vec.xyzw;

  /* Slot 44: 0x00000000 0x0A368055 0x0C3612AA 0x585045AC */
  MOV(_temp_vec,x, c[180].y);
  EXP(c181,y, R9.z);
  R5.x = _temp_vec.x;

  /* Slot 45: 0x00000000 0x0236A055 0x0C36106C 0xD250F374 */
  MOV(_temp_vec,z, c[181].y);
  MOV(c110,xyzw, R3);
  R5.z = _temp_vec.z;

  /* Slot 46: 0x00000000 0x008E601B 0x64AA1800 0x3F300FF8 */
  MAD(R3,xyzw, R6, c[115].y, c[115].x);

  /* Slot 47: 0x00000000 0x008E40AA 0x4436186E 0x9F700FF8 */
  MAD(R7,xyzw, R4.z, c[114], R10);

  /* Slot 48: 0x00000000 0x008D6100 0x85541BFC 0x30701358 */
  MAD(c107,w, -R8.x, c[107].z, c[107].w);

  /* Slot 49: 0x00000000 0x008D6000 0x85FE1AAA 0x10701358 */
  MAD(c107,w, R8.x, c[107].w, R8.z);

  /* Slot 50: 0x00000000 0x0240001B 0x2436C86D 0x5F80E36C */
  MUL(_temp_vec,xyzw, R2, R6);
  MOV(c109,xyz, R5);
  R8.xyzw = _temp_vec.xyzw;

  /* Slot 51: 0x00000000 0x0080001B 0x8436686D 0xDF600FF8 */
  MAD(R6,xyzw, R8, R3, R7);

  /* Slot 52: 0x00000000 0x00EC801B 0x6436186C 0x20708800 */
  DP4(oPos,x, R6, c[100]);

  /* Slot 53: 0x00000000 0x00ECA01B 0x6436186C 0x20704800 */
  DP4(oPos,y, R6, c[101]);

  /* Slot 54: 0x00000000 0x00ECC01B 0x6436186C 0x20702800 */
  DP4(oPos,z, R6, c[102]);

  /* Slot 55: 0x00000000 0x00ECE01B 0x6436186C 0x20701800 */
  DP4(oPos,w, R6, c[103]);

  /* Slot 56: 0x00000000 0x06ED001B 0x64361BFF 0x11780FF8 */
  DP4(_temp_vec,w, R6, c[104]);
  RCC(R1,x, R12.w);
  R7.w = _temp_vec.w;

  /* Slot 57: 0x00000000 0x0847401B 0xC4361BFD 0xD011E800 */
  MUL(oPos,xyz, R12, c[58]);
  RSQ(R1,w, R7.w);

  /* Slot 58: 0x00000000 0x004000FF 0x1554086C 0x21800FF8 */
  MUL(R8,w, R1.w, R0.z);

  /* Slot 59: 0x00000000 0x0087601B 0xC400286C 0x3070E800 */
  MAD(oPos,xyz, R12, R1.x, c[59]);

  /* Slot 60: 0x00000000 0x014000FF 0x85FE106C 0x20708831 */
  MAX(oPts,x, R8.w, v0.w);

  if (oPos.w == 0.0 || isinf(oPos.w)) {
    vtx.inv_w = 1.0;
  } else {
    vtx.inv_w = 1.0 / oPos.w;
  }
  oPos.x = 2.0 * (oPos.x - surfaceSize.x * 0.5) / surfaceSize.x;
  oPos.y = -2.0 * (oPos.y - surfaceSize.y * 0.5) / surfaceSize.y;
  if (clipRange.y != clipRange.x) {
    oPos.z = (oPos.z - clipRange.x)/(0.5*(clipRange.y - clipRange.x)) - 1;
  }
  if (oPos.w < 0.0) {
    oPos.xyz *= oPos.w;
  } else {
    oPos.w = 1.0;
  }
  float fogDistance = oFog.x;
  if (isinf(fogDistance)) {
    fogDistance = 0.0;
  }
  float fogFactor = fogParam[0] + fogDistance * fogParam[1];
  fogFactor -= 1.0;
  oFog.xyzw = vec4(fogFactor);

  vtx.D0 = clamp(oD0, 0.0, 1.0) * vtx.inv_w;
  vtx.D1 = clamp(oD1, 0.0, 1.0) * vtx.inv_w;
  vtx.B0 = clamp(oB0, 0.0, 1.0) * vtx.inv_w;
  vtx.B1 = clamp(oB1, 0.0, 1.0) * vtx.inv_w;
  vtx.Fog = oFog.x * vtx.inv_w;
  vtx.T0 = oT0 * vtx.inv_w;
  vtx.T1 = oT1 * vtx.inv_w;
  vtx.T2 = oT2 * vtx.inv_w;
  vtx.T3 = oT3 * vtx.inv_w;
  gl_Position = oPos;
  gl_PointSize = oPts.x;

}

nv2a: vertex shader compilation failed: 0(274) : error C1503: undefined variable "c107"
0(300) : error C1503: undefined variable "c107"
0(324) : error C1503: undefined variable "c113"
0(330) : error C1503: undefined variable "c113"
0(363) : error C1503: undefined variable "c176"
0(368) : error C1503: undefined variable "c177"
0(373) : error C1503: undefined variable "c178"
0(378) : error C1503: undefined variable "c179"
0(383) : error C1503: undefined variable "c180"
0(394) : error C1503: undefined variable "c108"
0(399) : error C1503: undefined variable "c181"
0(404) : error C1503: undefined variable "c110"
0(414) : error C1503: undefined variable "c107"
0(417) : error C1503: undefined variable "c107"
0(421) : error C1503: undefined variable "c109"
</details>

~~Ford Racing 2~~ Fixed - https://xemu.app/titles/454d0007

~~Unreal Championship 2: The Liandri Conflict~~ Fixed - https://xemu.app/titles/4d570021

Flight Academy - https://xemu.app/titles/41510002
 
<details close>
<summary>Failing Fragment Shader from Flight Academy </summary>
<br>
#version 400

uniform vec2 clipRange;
uniform vec2 surfaceSize;

uniform vec4 c[192];

uniform vec4 fogColor;
uniform float fogParam[2];

#define fogPlane c[0x39]
#define texMat0 mat4(c[0x44], c[0x44+1], c[0x44+2], c[0x44+3])
#define texMat1 mat4(c[0x4c], c[0x4c+1], c[0x4c+2], c[0x4c+3])
#define texMat2 mat4(c[0x54], c[0x54+1], c[0x54+2], c[0x54+3])
#define texMat3 mat4(c[0x5c], c[0x5c+1], c[0x5c+2], c[0x5c+3])

vec4 oPos = vec4(0.0,0.0,0.0,1.0);
vec4 oD0 = vec4(0.0,0.0,0.0,1.0);
vec4 oD1 = vec4(0.0,0.0,0.0,1.0);
vec4 oB0 = vec4(0.0,0.0,0.0,1.0);
vec4 oB1 = vec4(0.0,0.0,0.0,1.0);
vec4 oPts = vec4(0.0,0.0,0.0,1.0);
vec4 oFog = vec4(1.0,0.0,0.0,1.0);
vec4 oT0 = vec4(0.0,0.0,0.0,1.0);
vec4 oT1 = vec4(0.0,0.0,0.0,1.0);
vec4 oT2 = vec4(0.0,0.0,0.0,1.0);
vec4 oT3 = vec4(0.0,0.0,0.0,1.0);

vec4 decompress_11_11_10(int cmp) {
    float x = float(bitfieldExtract(cmp, 0,  11)) / 1023.0;
    float y = float(bitfieldExtract(cmp, 11, 11)) / 1023.0;
    float z = float(bitfieldExtract(cmp, 22, 10)) / 511.0;
    return vec4(x, y, z, 1);
}
struct VertexData {
  float inv_w;
  vec4 D0;
  vec4 D1;
  vec4 B0;
  vec4 B1;
  float Fog;
  vec4 T0;
  vec4 T1;
  vec4 T2;
  vec4 T3;
};
noperspective out VertexData g_vtx;
#define vtx g_vtx

layout(location = 0) in vec4 v0;
layout(location = 1) in vec4 v1;
layout(location = 2) in vec4 v2;
layout(location = 3) in vec4 v3;
layout(location = 4) in vec4 v4;
layout(location = 5) in vec4 v5;
layout(location = 6) in vec4 v6;
layout(location = 7) in vec4 v7;
layout(location = 8) in vec4 v8;
layout(location = 9) in vec4 v9;
layout(location = 10) in vec4 v10;
layout(location = 11) in vec4 v11;
layout(location = 12) in vec4 v12;
layout(location = 13) in vec4 v13;
layout(location = 14) in vec4 v14;
layout(location = 15) in vec4 v15;

#define position      v0
#define weight        v1
#define normal        v2.xyz
#define diffuse       v3
#define specular      v4
#define fogCoord      v5.x
#define pointSize     v6
#define backDiffuse   v7
#define backSpecular  v8
#define texture0      v9
#define texture1      v10
#define texture2      v11
#define texture3      v12
#define reserved1     v13
#define reserved2     v14
#define reserved3     v15

uniform vec4 ltctxa[26];
uniform vec4 ltctxb[52];
uniform vec4 ltc1[20];

#define projectionMat mat4(c[0x04], c[0x04+1], c[0x04+2], c[0x04+3])
#define compositeMat mat4(c[0x00], c[0x00+1], c[0x00+2], c[0x00+3])

#define texPlaneS0 c[0x40 + 0]
#define texPlaneT0 c[0x40 + 1]
#define texPlaneQ0 c[0x40 + 2]
#define texPlaneR0 c[0x40 + 3]

#define texPlaneS1 c[0x48 + 0]
#define texPlaneT1 c[0x48 + 1]
#define texPlaneQ1 c[0x48 + 2]
#define texPlaneR1 c[0x48 + 3]

#define texPlaneS2 c[0x50 + 0]
#define texPlaneT2 c[0x50 + 1]
#define texPlaneQ2 c[0x50 + 2]
#define texPlaneR2 c[0x50 + 3]

#define texPlaneS3 c[0x58 + 0]
#define texPlaneT3 c[0x58 + 1]
#define texPlaneQ3 c[0x58 + 2]
#define texPlaneR3 c[0x58 + 3]

#define modelViewMat0 mat4(c[0x08], c[0x08+1], c[0x08+2], c[0x08+3])
#define modelViewMat1 mat4(c[0x10], c[0x10+1], c[0x10+2], c[0x10+3])
#define modelViewMat2 mat4(c[0x18], c[0x18+1], c[0x18+2], c[0x18+3])
#define modelViewMat3 mat4(c[0x20], c[0x20+1], c[0x20+2], c[0x20+3])

#define invModelViewMat0 mat4(c[0x0c], c[0x0c+1], c[0x0c+2], c[0x0c+3])
#define invModelViewMat1 mat4(c[0x14], c[0x14+1], c[0x14+2], c[0x14+3])
#define invModelViewMat2 mat4(c[0x1c], c[0x1c+1], c[0x1c+2], c[0x1c+3])
#define invModelViewMat3 mat4(c[0x24], c[0x24+1], c[0x24+2], c[0x24+3])

#define eyePosition c[0x38]

#define lightAmbientColor(i) ltctxb[0x00 + (i)*6].xyz
#define lightDiffuseColor(i) ltctxb[0x01 + (i)*6].xyz
#define lightSpecularColor(i) ltctxb[0x02 + (i)*6].xyz

#define lightSpotFalloff(i) ltctxa[0x00 + (i)*2].xyz
#define lightSpotDirection(i) ltctxa[0x01 + (i)*2]

#define lightLocalRange(i) ltc1[0x04 + (i)].x

#define sceneAmbientColor ltctxa[0x11].xyz
#define materialEmissionColor ltctxa[0x13].xyz

uniform mat4 invViewport;

void main() {
/* Skinning mode 0 */
vec4 tPosition = (position * modelViewMat0).xyzw;
vec3 tNormal = (vec4(normal, 0.0) * invModelViewMat0).xyz;
/* Texgen for stage 0 */
oT0.x = texture0.x;
oT0.y = texture0.y;
oT0.z = texture0.z;
oT0.w = texture0.w;
/* Texgen for stage 1 */
oT1.x = texture1.x;
oT1.y = texture1.y;
oT1.z = texture1.z;
oT1.w = texture1.w;
/* Texgen for stage 2 */
oT2.x = texture2.x;
oT2.y = texture2.y;
oT2.z = texture2.z;
oT2.w = texture2.w;
/* Texgen for stage 3 */
oT3.x = texture3.x;
oT3.y = texture3.y;
oT3.z = texture3.z;
oT3.w = texture3.w;
oT0 = oT0 * texMat0;
  oD0 = diffuse;
  oD1 = specular;
  oB0 = backDiffuse;
  oB1 = backSpecular;
  tPosition = position;
   oPos = invViewport * (tPosition * compositeMat);
   oPos.z = oPos.z * 2.0 - oPos.w;
  float d_e = length(position * modelViewMat0);
  oPts.x = 1/sqrt(nan + nan*d_e + inf*d_e*d_e) + -0.032258;
  oPts.x = min(oPts.x*62.000000 + 2.000000, 64.0) * 1;
  vtx.inv_w = 1.0 / oPos.w;
  oFog.xyzw = vec4(1.0);

  vtx.D0 = clamp(oD0, 0.0, 1.0) * vtx.inv_w;
  vtx.D1 = clamp(oD1, 0.0, 1.0) * vtx.inv_w;
  vtx.B0 = clamp(oB0, 0.0, 1.0) * vtx.inv_w;
  vtx.B1 = clamp(oB1, 0.0, 1.0) * vtx.inv_w;
  vtx.Fog = oFog.x * vtx.inv_w;
  vtx.T0 = oT0 * vtx.inv_w;
  vtx.T1 = oT1 * vtx.inv_w;
  vtx.T2 = oT2 * vtx.inv_w;
  vtx.T3 = oT3 * vtx.inv_w;
  gl_Position = oPos;
  gl_PointSize = oPts.x;

}

nv2a: vertex shader compilation failed: 0(170) : error C1503: undefined variable "nan"
0(170) : error C1503: undefined variable "nan"
0(170) : error C1503: undefined variable "inf"

Resetting rate control (149741 samples)
</details>
### Bug Description
When going in-game on NHL 2002 + Unreal Championship 2: The Liandri Conflict + Flight Academy and saving in Ford racing 2, the games freezes then crashes. it also corrupts the save data for Ford racing 2.

Steps to reproduce this issue:
NHL 2002
1. Insert disk
2. From to main main go to quick and start a match
3. The game freezes for 5 mins
4. game crashed

Ford racing 2
1. Insert disk
2. create a save
3. game crashes

### Expected Behavior
Games should make it further in-game

<ul>
<li>Version: build-202106020756( <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5/hovercard" href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context
NHL 2002 broken intro  pictures:https://imgur.com/a/B6sCm1m

**Comment by MasonT8198** [comment]
Thanks for squashing this issue down

**Comment by RageXbox** [comment]
Now also affects https://xemu.app/titles/41510002/#Flight-Academy
Here's a log for it: [flightacadamy.log](https://github.com/mborgerson/xemu/files/7929592/flightacadamy.log)

**Comment by Triticum0** [comment]
Updated

**Comment by Triticum0** [comment]
@abaire I tested Flight Acadamy and the Fragment Shader Fail the same
<details close>
<summary>Failing Fragment Shader from Flight Academy </summary>
<br>
#version 400

uniform vec2 clipRange;
uniform vec2 surfaceSize;

uniform vec4 c[192];

uniform vec4 fogColor;
uniform float fogParam[2];

#define fogPlane c[0x39]
#define texMat0 mat4(c[0x44], c[0x44+1], c[0x44+2], c[0x44+3])
#define texMat1 mat4(c[0x4c], c[0x4c+1], c[0x4c+2], c[0x4c+3])
#define texMat2 mat4(c[0x54], c[0x54+1], c[0x54+2], c[0x54+3])
#define texMat3 mat4(c[0x5c], c[0x5c+1], c[0x5c+2], c[0x5c+3])

vec4 oPos = vec4(0.0,0.0,0.0,1.0);
vec4 oD0 = vec4(0.0,0.0,0.0,1.0);
vec4 oD1 = vec4(0.0,0.0,0.0,1.0);
vec4 oB0 = vec4(0.0,0.0,0.0,1.0);
vec4 oB1 = vec4(0.0,0.0,0.0,1.0);
vec4 oPts = vec4(0.0,0.0,0.0,1.0);
vec4 oFog = vec4(1.0,0.0,0.0,1.0);
vec4 oT0 = vec4(0.0,0.0,0.0,1.0);
vec4 oT1 = vec4(0.0,0.0,0.0,1.0);
vec4 oT2 = vec4(0.0,0.0,0.0,1.0);
vec4 oT3 = vec4(0.0,0.0,0.0,1.0);

vec4 decompress_11_11_10(int cmp) {
    float x = float(bitfieldExtract(cmp, 0,  11)) / 1023.0;
    float y = float(bitfieldExtract(cmp, 11, 11)) / 1023.0;
    float z = float(bitfieldExtract(cmp, 22, 10)) / 511.0;
    return vec4(x, y, z, 1);
}
struct VertexData {
  float inv_w;
  vec4 D0;
  vec4 D1;
  vec4 B0;
  vec4 B1;
  float Fog;
  vec4 T0;
  vec4 T1;
  vec4 T2;
  vec4 T3;
};
noperspective out VertexData g_vtx;
#define vtx g_vtx

layout(location = 0) in vec4 v0;
layout(location = 1) in vec4 v1;
layout(location = 2) in vec4 v2;
layout(location = 3) in vec4 v3;
layout(location = 4) in vec4 v4;
layout(location = 5) in vec4 v5;
layout(location = 6) in vec4 v6;
layout(location = 7) in vec4 v7;
layout(location = 8) in vec4 v8;
layout(location = 9) in vec4 v9;
layout(location = 10) in vec4 v10;
layout(location = 11) in vec4 v11;
layout(location = 12) in vec4 v12;
layout(location = 13) in vec4 v13;
layout(location = 14) in vec4 v14;
layout(location = 15) in vec4 v15;

#define position      v0
#define weight        v1
#define normal        v2.xyz
#define diffuse       v3
#define specular      v4
#define fogCoord      v5.x
#define pointSize     v6
#define backDiffuse   v7
#define backSpecular  v8
#define texture0      v9
#define texture1      v10
#define texture2      v11
#define texture3      v12
#define reserved1     v13
#define reserved2     v14
#define reserved3     v15

uniform vec4 ltctxa[26];
uniform vec4 ltctxb[52];
uniform vec4 ltc1[20];

#define projectionMat mat4(c[0x04], c[0x04+1], c[0x04+2], c[0x04+3])
#define compositeMat mat4(c[0x00], c[0x00+1], c[0x00+2], c[0x00+3])

#define texPlaneS0 c[0x40 + 0]
#define texPlaneT0 c[0x40 + 1]
#define texPlaneR0 c[0x40 + 2]
#define texPlaneQ0 c[0x40 + 3]

#define texPlaneS1 c[0x48 + 0]
#define texPlaneT1 c[0x48 + 1]
#define texPlaneR1 c[0x48 + 2]
#define texPlaneQ1 c[0x48 + 3]

#define texPlaneS2 c[0x50 + 0]
#define texPlaneT2 c[0x50 + 1]
#define texPlaneR2 c[0x50 + 2]
#define texPlaneQ2 c[0x50 + 3]

#define texPlaneS3 c[0x58 + 0]
#define texPlaneT3 c[0x58 + 1]
#define texPlaneR3 c[0x58 + 2]
#define texPlaneQ3 c[0x58 + 3]

#define modelViewMat0 mat4(c[0x08], c[0x08+1], c[0x08+2], c[0x08+3])
#define modelViewMat1 mat4(c[0x10], c[0x10+1], c[0x10+2], c[0x10+3])
#define modelViewMat2 mat4(c[0x18], c[0x18+1], c[0x18+2], c[0x18+3])
#define modelViewMat3 mat4(c[0x20], c[0x20+1], c[0x20+2], c[0x20+3])

#define invModelViewMat0 mat4(c[0x0c], c[0x0c+1], c[0x0c+2], c[0x0c+3])
#define invModelViewMat1 mat4(c[0x14], c[0x14+1], c[0x14+2], c[0x14+3])
#define invModelViewMat2 mat4(c[0x1c], c[0x1c+1], c[0x1c+2], c[0x1c+3])
#define invModelViewMat3 mat4(c[0x24], c[0x24+1], c[0x24+2], c[0x24+3])

#define eyePosition c[0x38]

#define lightAmbientColor(i) ltctxb[0x00 + (i)*6].xyz
#define lightDiffuseColor(i) ltctxb[0x01 + (i)*6].xyz
#define lightSpecularColor(i) ltctxb[0x02 + (i)*6].xyz

#define lightSpotFalloff(i) ltctxa[0x00 + (i)*2].xyz
#define lightSpotDirection(i) ltctxa[0x01 + (i)*2]

#define lightLocalRange(i) ltc1[0x04 + (i)].x

#define sceneAmbientColor ltctxa[0x11].xyz
#define materialEmissionColor ltctxa[0x13].xyz

uniform mat4 invViewport;

void main() {
/* Skinning mode 0 */
vec4 tPosition = (position * modelViewMat0).xyzw;
vec3 tNormal = (vec4(normal, 0.0) * invModelViewMat0).xyz;
/* Texgen for stage 0 */
oT0.x = texture0.x;
oT0.y = texture0.y;
oT0.z = texture0.z;
oT0.w = texture0.w;
/* Texgen for stage 1 */
oT1.x = texture1.x;
oT1.y = texture1.y;
oT1.z = texture1.z;
oT1.w = texture1.w;
/* Texgen for stage 2 */
oT2.x = texture2.x;
oT2.y = texture2.y;
oT2.z = texture2.z;
oT2.w = texture2.w;
/* Texgen for stage 3 */
oT3.x = texture3.x;
oT3.y = texture3.y;
oT3.z = texture3.z;
oT3.w = texture3.w;
oT0 = oT0 * texMat0;
  oD0 = diffuse;
  oD1 = specular;
  oB0 = backDiffuse;
  oB1 = backSpecular;
  tPosition = position;
   oPos = invViewport * (tPosition * compositeMat);
   oPos.z = oPos.z * 2.0 - oPos.w;
  float d_e = length(position * modelViewMat0);
  oPts.x = 1/sqrt(nan + nan*d_e + inf*d_e*d_e) + -0.032258;
  oPts.x = min(oPts.x*62.000000 + 2.000000, 64.0) * 1;
  vtx.inv_w = 1.0 / oPos.w;
  oFog.xyzw = vec4(1.0);

  vtx.D0 = clamp(oD0, 0.0, 1.0) * vtx.inv_w;
  vtx.D1 = clamp(oD1, 0.0, 1.0) * vtx.inv_w;
  vtx.B0 = clamp(oB0, 0.0, 1.0) * vtx.inv_w;
  vtx.B1 = clamp(oB1, 0.0, 1.0) * vtx.inv_w;
  vtx.Fog = oFog.x * vtx.inv_w;
  vtx.T0 = oT0 * vtx.inv_w;
  vtx.T1 = oT1 * vtx.inv_w;
  vtx.T2 = oT2 * vtx.inv_w;
  vtx.T3 = oT3 * vtx.inv_w;
  gl_Position = oPos;
  gl_PointSize = oPts.x;

}


nv2a: vertex shader compilation failed: 0(170) : error C1503: undefined variable "nan"
0(170) : error C1503: undefined variable "nan"
0(170) : error C1503: undefined variable "inf

**Comment by abaire** [comment]
@Triticum0 thanks! I suggest we either put that in a new bug specific to Flight Academy and close this one, or rename this one to just track the FA bug since the others are fixed.

**Comment by Triticum0** [comment]
@abaire  NHL 2002 Still Crashes But The Fragment Shader Fail Different Take a look

**Comment by abaire** [comment]
@Triticum0 interesting, that should be another new bug, it's a totally different underlying error.

You can point at https://github.com/mborgerson/xemu/blob/8334f294df46351eaed4d92eb3a264f9e7cc650b/hw/xbox/nv2a/vsh.c#L427 in the bug, I believe that's the underlying problem. We should probably just assert instead of having a TODO that generates an invalid shader.


UPDATE for posterity: In #1080 I added a CPU-based renderer to handle writable const/context registers. In theory we could implement a path for NHL 2002 that falls back to running the shader on the CPU and uploads pre-transformed results to a special vertex shader path.

I'm still pondering whether we could better handle writable context registers in the vertex shader, however, using transform feedback to capture any modified results. Roughly we'd decode the vsh and identify any writes to context registers. Generate `out vec4 wr_c<register_num>` variables for each, initializing them to the appropriate `c[register_num]` uniform and flagging them via `glTransformFeedbackVaryings`. After the draw we'd fetch the values out of the transform feedback buffer and update the CPU-side state with the value(s) associated with the last relevant vertex in order to match HW behavior.

**Comment by abaire** [comment]
Hey @Triticum0 when you have a chance can you split this bug into two and close it? 

It still shows up for the games that are fixed (e.g.,  https://xemu.app/titles/454d0007/) and the two remaining broken games are due to two entirely unrelated issues that will need to be addressed separately, so tracking them in one bug is misleading.

**Comment by Triticum0** [comment]
Done
