### ISSUE TITLE
Unknown front face

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#321]
### Title Information
Titles: 
Whiplash (45530011)
Project: Snowblind (45530019)
https://xemu.app/titles/45530011/#Whiplash
https://xemu.app/titles/45530019/#Project-Snowblind

### Bug Description
Game crashes with this assertion before the intro
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L1707-L1708

Steps to reproduce this issue:
1. Insert disk
2. Game crashes

### Expected Behavior

It should make it into the intro

### Version
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by mborgerson** [comment]
What is the message printed (`Unknown front face: 0x...`)

**Comment by Triticum0** [comment]
sorry i fixed it. it hit the assert 1666

**Comment by abaire** [comment]
This still fails with Version: 0.6.2-5-gfee48fd58b

The unknown front face is `0x0` (for Snowblind, I don't have Whiplash)

I added a test case to https://github.com/abaire/nxdk_pgraph_tests and found that on hardware all unknown values ~~seem to be mapped to CCW.~~ are silently ignored.
