### ISSUE TITLE
[Assertion] in_pitch >= in_width * 2

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#330]
### Upon ejecting the disk
https://xemu.app/titles/4d53005f/#Voodoo-Vince
https://xemu.app/titles/54540004/#Serious-Sam

### Crashes After Finishing Intro
https://xemu.app/titles/4d57001c/#Midway-Arcade-Treasures
https://xemu.app/titles/41510003/#Sentou-Yousei-Yukikaze-Yousei-no-Mau-Sora 
(This should be in the intros, someone didn't file the report properly)
https://xemu.app/titles/57450001/#Ultimate-Beach-Soccer

### Bug Description
Known games with this issue:
- Midway Arcade Treasures* 
- Sentou Yousei Yukikaze Yousei no Mau Sora*
- Ultimate-Beach-Soccer*
- Voodoo Vince
- Serious Sam
- All games that use pvideo to display intro videos

The above games cause an assertion failure if you attempt to load an ISO while the game intro videos are playing
Additionally games with an Asterisk crash regardless of the game is ejected or not.
https://github.com/mborgerson/xemu/blob/72b511c091895b6ea267ad1305afd94ffe580135/hw/xbox/nv2a/pgraph.c#L4303

Reproduction:
1: Load the game and close Xemu so it runs it by default on the next boot
2: Open Xemu, and wait until the game's intro videos are playing
3: Load Disc (It can be any ISO, even the same game)
4: Assertion failed.
xemu: ../hw/xbox/nv2a/pgraph.c:4897: pgraph_render_display_pvideo_overlay: Assertion in_pitch >= in_width * 2' failed.

Reproduction Alternative:
1: Load game and close Xemu so it runs by default on next boot
2: Open Xemu and Eject disk when the game's intro videos are playing
3: Assertion failed.

Reproduction video on Voodoo Vince:

https://user-images.githubusercontent.com/105917902/169626030-474f3638-8323-4b2b-ab58-f0518077f34d.mp4

### Expected Behavior
I should be able to make it to the menus without a crash

<h3>Version</h3>
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

Additional Context
The games on the list crash automatically. I Can confirm from my testing. 
Also, I adapted so of this issue from [doinkers](https://github.com/doinkers) So I big thank for his help

**Comment by Triticum0** [comment]
Retest the games a couple of days ago they are still broken

**Comment by abaire** [comment]
It would be very interesting to run this under a debugger to see what the `in_pitch` and `in_width` are actually set to.

This assert is in `pgraph_render_display_pvideo_overlay` and the assert just prior to the failing one already verifies that the color format is `NV_PVIDEO_FORMAT_COLOR_LE_CR8YB8CB8YA8` which implies 2 bytes per pixel.

**Comment by Triticum0** [comment]
@abaire You want me to use anything special or just use the monitor

**Comment by abaire** [comment]
@Triticum0 if #947 is really a dup of this we should merge the repro instructions into this bug. I have both of the games cited in that issue and am able to reproduce using those instructions but someone would have to check the values in the assert with the games in this bug to verify that it's truly a duplicate.

Reproducing by ejecting Voodoo Vince during the initial FMV, I see that `in_width` is set to 2047, `in_pitch` is only 1280.
I suspect that this is a red herring, as `NV_PVIDEO_SIZE_IN` is set to `0xFFFFFFFF` which seems likely to be a sentinel value that would cause some special behavior on HW. I'll put together a test case to verify how this behaves.

Note that `NV_PVIDEO_SIZE_OUT`, `NV_PVIDEO_POINT_IN`, and `NV_PVIDEO_POINT_OUT` all look reasonable, as do the video location registers (base/limit/offset).

**Comment by abaire** [comment]
> @abaire You want me to use anything special or just use the monitor

The easiest thing would be to run a debug version of xemu under gdb, let it hit the assert and you can step back a few stack frames to investigate the values. I'm specifically interested in `d->pvideo.regs[NV_PVIDEO_SIZE_IN]` at the time of the assert.

Given that I've found something that looks odd with the "eject" path I'll probably have a prospective fix in a few hours so you can also wait for that if you're not set up to run under the debugger.

**Comment by abaire** [comment]
On hardware setting SIZE_IN to 0xFFFFFFFF causes the overlay to be torn down immediately. It also seems to prevent it from being displayed again even with a valid size though, so I'm missing some additional component of the behavior.

**Comment by Triticum0** [comment]
Yeah, So you want me to merge how to reproduce the issue into the original issue. Done

**Comment by Triticum0** [comment]
@abaire I got gdb running with Xemu started the game got to the assertion then use bt. Do I need to enable trace-event nv2a_pgraph_* on to get any useful info information?

**Comment by abaire** [comment]
> @abaire I got gdb running with Xemu started the game got to the assertion then use bt. Do I need to enable trace-event nv2a_pgraph_* on to get any useful info information?

No, all the info you need should be in the stack frame, you just need to navigate back to the frame that has the assert and inspect the value of `d->pvideo.regs[NV_PVIDEO_SIZE_IN]`

I just pushed a draft PR #1178 that tears down the overlay when SIZE_IN is set to 0xFFFFFFFF, can you check to see if that resolves the problem? 

I still need to do some investigation as it also appears to leave my test program in a bad state where I can never get the overlay to come back, so there's some additional reset behavior that I'm missing.

**Comment by Triticum0** [comment]
@abaire Is this what you needed?
```
0x00007ffcb444d533 in KERNELBASE!DebugBreak () from /c/WINDOWS/System32/KERNELBASE.dll
(gdb) bt full
#0  0x00007ffcb444d533 in KERNELBASE!DebugBreak () from /c/WINDOWS/System32/KERNELBASE.dll
No symbol table info available.
#1  0x00007ffcb5aabb49 in msvcrt!_assert () from /c/WINDOWS/System32/msvcrt.dll
No symbol table info available.
#2  0x00007ff647ea6f88 in pgraph_render_display_pvideo_overlay (d=d@entry=0x1f0f905c040) at ../hw/xbox/nv2a/pgraph.c:5098
        pg = 0x1f0f907ec98
        enabled = <optimized out>
        base = 0
        limit = 134217727
        offset = 53141504
        in_width = 2047
        in_height = 2047
        in_pitch = 1472
        in_color = <optimized out>
        out_width = 3042964960
        out_height = 198
        out_x = 0
        out_y = 0
        color_key_enabled = <optimized out>
        color_key = <optimized out>
        end = <optimized out>
        tex_rgba = <optimized out>
#3  0x00007ff647ea7250 in pgraph_render_display (d=d@entry=0x1f0f905c040, surface=surface@entry=0x1f0f8006050)
    at ../hw/xbox/nv2a/pgraph.c:5217
        pg = 0x1f0f907ec98
        width = 640
        height = 480
        pline_offset = 2560
        pstart_addr = 15687680
        pline_compare = 1023
        line_offset = 1
        recreate = <optimized out>
        DrawBuffers = {36064}
#4  0x00007ff647eb1c0d in pgraph_gl_sync (d=d@entry=0x1f0f905c040) at ../hw/xbox/nv2a/pgraph.c:5254
        pline_offset = 2560
        pstart_addr = 15687680
        pline_compare = 1023
        surface = 0x1f0f8006050
#5  0x00007ff647e9018a in process_requests (d=d@entry=0x1f0f905c040) at ../hw/xbox/nv2a/pfifo.c:465
No locals.
#6  0x00007ff647e91069 in pfifo_thread (arg=arg@entry=0x1f0f905c040) at ../hw/xbox/nv2a/pfifo.c:486
        d = 0x1f0f905c040
#7  0x00007ff648081749 in win32_start_routine (arg=0x1f0f87afd00) at ../util/qemu-thread-win32.c:355
        data = 0x1f0f87afd00
        start_routine = 0x7ff647e91005 <pfifo_thread>
        thread_arg = 0x1f0f905c040
#8  0x00007ffcb5abaf5a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
No symbol table info available.
#9  0x00007ffcb5abb02c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
No symbol table info available.
#10 0x00007ffcb58d7034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
No symbol table info available.
#11 0x00007ffcb6aa2651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
No symbol table info available.
#12 0x0000000000000000 in ?? ()

```

**Comment by Triticum0** [comment]
I used a ` bt full` but I'm not sure how you would of went about doing it

**Comment by abaire** [comment]
Yup, that confirms that it's the same 0xFFFFFFFF sentinel case. 

I've updated my PR to more accurately reproduce hardware (it shouldn't actually tear down the overlay, it should just treat input sizes > outputs as the output size). Can you double check that it still works for the `Crashes After Finishing Intro` games?

**Comment by brad86m** [comment]
This still happens. Been like this for many years.

Every time I got to eject a disc to load a new one, I get the fatal error popup. Abort, Retry, Ignore options do nothing. I end up having to open the ini file to manually remove the current game entry.

**Comment by antangelo** [comment]
xemu has not used the ini file for configuration for years now, are you sure you are running the latest version?
