### ISSUE TITLE
Airforce Delta Storm/Deadly Skies: Hangs when Certain Audio Plays

### ISSUE THREAD

**Issue by 4XPG** [xemu-project/xemu#361]
### Title Information

* Titles: AirForce Delta Storm (NTSC-U), Deadly Skies (PAL), Airforce Delta II (NTSC-J)
* https://xemu.app/titles/4b4e0002/#AirForce-Delta-Storm

### Bug Description

The emulator hangs one second after what should've been a missile alert sound effect or the second voiced dialogue in the mission plays. Can be reproduced by letting the game plays demo reel too.

Steps to reproduce this issue:
1. Play any mission
2. Let any enemy fire a missile at you OR wait until the second voiced chatter in the mission plays (happens at around 4 minutes mark on first mission)
3. The audio then suddenly stops, and the emulator becomes not responding afterwards

OR

1. Don't press anything at title screen and let the game loads demo reel. The emulator will hang shortly afterwards.

### Expected Behavior

The missile alert beep should play and loops until the missile misses/hits you without freezing the emulator. The voiced dialogue should play without freezing the emulator.

AND

The game displays demo reel without freezing.

This problem has persisted since audio was first implemented.

### Version

* Version: 0.5.4-7-ga7f3f8f212
* Last-known Working: 0.4.0-22-gbdd8375ba2

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 Pro Build 19042.685		| 
| CPU			| Ryzen 5 3600 ~3.6GHz			| 
| Graphics Device	| Nvidia GeForce RTX 3070			| 
| Graphics Driver	| 27.21.14.6589		| 

### Additional Context

Log is provided. Using Deadly Skies as sample.
[xemu.log](https://github.com/mborgerson/xemu/files/6687327/xemu.log)

**Comment by 4XPG** [comment]
As of 0.6.2-51-g3fd15218c7, fixed for NTSC-U version (Airforce Delta Storm) but not for PAL/NTSC-J (Deadly Skies/Airforce Delta II)

In a not related bug, the NTSC-U version doesn't let me to save game as well whereas saving works normally in other two regions.

Log is provided. Using Airforce Delta II (NTSC-J) as example.
[xemu.log](https://github.com/mborgerson/xemu/files/7880335/xemu.log)

**Comment by GrowlerEA18G** [comment]
Deadly Skies (PAL and JP version of Airforce Delta Storm) still has crash issues when enemy launching at the player. This issue doesnt present in NTSC version of the game

**Comment by ThePilotX** [comment]
As of 0.7.127 still crashing with enemy missile launch, just with Deadly Skies (PAL/NTSC-J) :(

**Comment by qrfsgame** [comment]
Even with the current latest version 0.8.20, this issue is not resolved in NTSC-J.
It also doesn't resolve the issue of the emulator freezing during the opening demo.

**Comment by Triticum0** [comment]
Test with Real time dps to see if it makes a differences

**Comment by ThePilotX** [comment]
> Test with Real time dps to see if it makes a differences

Just tested it, unfortunately it still crashes with DPS as soon as the missile warning appears, it's already been fixed ages ago for the US version of the game, fix just needs to be applied for PAL/NTSC-J version

**Comment by TheSloth1218** [comment]
same here still affecting both pal and ntsc-j versions wish it was fixed soon

**Comment by Megalith9** [comment]
Issue still persist on version 0.8.96, only on Deadly Skies (EU)
Airforce Delta Storm works properly and without errors.

My specs:

CPU:          11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Driver:       4.0.0 NVIDIA 576.88
Shader:       4.00 NVIDIA via Cg compiler

Version:      0.8.96
Branch:       master
Commit:       98a3974290618086de5132d27c8ede736f9d93ea
Date:         Tue Jul 29 21:53:42 UTC 2025

**Comment by 4XPG** [comment]
<img width="1282" height="992" alt="Image" src="https://github.com/user-attachments/assets/f7d7b884-5d32-4c8a-82aa-ae0e7dce9c96" />
Still not fixed yet on latest master (v0.8.115) with DSP enabled or disabled

**Comment by Megalith9** [comment]
Issue still persists on Xemu version v0.8.136.

Version:      0.8.136
Commit:       fc24584ce88f0915ad7f04775bb7712c2e3f49ee
Date:         Mon Jun  8 05:42:55 UTC 2026
CPU:          11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Driver:       4.0.0 NVIDIA 596.21
Shader:       4.00 NVIDIA via Cg compiler

<img width="1278" height="948" alt="Image" src="https://github.com/user-attachments/assets/fe81e2a6-a7fa-4525-9133-2aca9bffc5fb" />
