### ISSUE TITLE
Halo 2: Able to see other objects through objects close to you

### ISSUE THREAD

**Issue by Alastair0100** [xemu-project/xemu#55]
Also can depend on viewing angle aswell as how close objects are to you from my testing

Title: 4d530064

![image](https://user-images.githubusercontent.com/40572266/97756179-5d9e5f00-1af2-11eb-8a3a-0af083ec9825.png)
![image](https://user-images.githubusercontent.com/40572266/97756201-6858f400-1af2-11eb-91a9-5894d618aa83.png)
![image](https://user-images.githubusercontent.com/40572266/97756212-6bec7b00-1af2-11eb-8968-8966bf63237d.png)
![image](https://user-images.githubusercontent.com/40572266/97756221-6f800200-1af2-11eb-9fc6-327b9d5b6d46.png)

**Comment by Shoegzer** [comment]
Confirmed in testing here too.

Relevant test specs:
* OS: Linux Mint 20.3 / kernel 5.131
* GPU: NVidia GTX 3070 / driver 470.86
* Commit tested: 3fd15218c76cedd89496db637c7ef5369ef35a63

**Comment by Triticum0** [comment]
This also affects Wallace & Gromit in Project Zoo, Miami Vice, Tom Clancy's Splinter Cell and Serious Sam

**Comment by BiatuAutMiahn** [comment]
In #266, I mention when this behaviour started in Halo 2.

**Comment by RageXbox** [comment]
Here’s a log for this.
[Halo 2 seethrough.log](https://github.com/mborgerson/xemu/files/7901151/Halo.2.seethrough.log)

**Comment by abaire** [comment]
This looks like it may be a depth buffer precision issue, stepping through the draws in renderdoc I see depth buffer values for the more distant draws that are suspiciously close to but less than the nearby correct nearer geometry with odd discontinuities (e.g., if I follow the plane of a wall that is being cut out, I see values that follow a linear trend then jump to higher values where the earlier draw is peeking through, then resume within the expected interpolated range after the slice).

Halo2 uses a non-standard clip range:
```
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_CLIP_MIN<0x394> (0x437FFFFF => 255.999985)
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_CLIP_MAX<0x398> (0x4B7FFFFF => 16777215.000000)
```
though it at least uses the same range throughout all of the draws in the frame I traced.

I've previously found that the technique xemu employs to attempt to map screen coords produced by the nv2a shaders back into OpenGL-friendly NDC has some issues when dealing with unusual clip ranges (e.g., #843). This may be part of what is happening here.

**Comment by Shootfast** [comment]
Not sure if this is helpful at all, but in my naive attempt to debug this issue in Renderdoc, I found that commenting out [this](https://github.com/xemu-project/xemu/blob/d8fa50e524c22f85ecb2e43108fd6a5501744351/hw/xbox/nv2a/vsh.c#L840) line of the vertex shader completely fixes the "see-through" issue (though also adds other problems).

Might that point away from it being a depth buffer precision issue, and perhaps point towards it being a problem converting the screen space to clip space?

**Comment by polymetal0** [comment]
Thanks to your comment, I accidentally got Skybox working!

**Comment by polymetal0** [comment]
Upon further research, I'm positive @Shootfast is right about that line being the issue. 
Completely removing that if statement fixes the see through issue, but it does break other things specifically in Halo 2.

I'm pretty sure it has to do with the normalization taking place right after that statement, but I don't know if it is possible to get the true range for oPos.w to get sth like this:

 ```
if (z_perspective) {
        mstring_append(body, 
            //"    oPos.z = oPos.w;\n"
            "    oPos.z = 2.0 * (oPos.w - /*newClipRangeMin*/) / (/*newClipRangeMax*/ - /*newClipRangeMin*/) - 1.0;\n" 
        );
    } else {
        mstring_append(body, 
            "  if (clipRange.y != clipRange.x) {\n"
            "    oPos.z = 2.0 * (oPos.z - clipRange.x) / ((clipRange.y - clipRange.x)) - 1.0;\n"
            "  }\n"  
        );
    }  
   mstring_append(body,
    //"  if (clipRange.y != clipRange.x) {\n"
    //"    oPos.z = 2.0 * (oPos.z - clipRange.x) / ((clipRange.y - clipRange.x)) - 1.0 ;\n"
    //"  }\n" 
```
   
I have tried all combinations I could come up with and nothing worked, does anyone have any clue as to how to proceed?

Edit: maybe related to #843 ?

New edit: my bad, it was actually clamping z to 1 what brought dynamic shadows back. But this still confirms that there's something wrong with oPos.w's range

**Comment by polymetal0** [comment]
Some screenshots:

Latest release:
![halo2](https://github.com/xemu-project/xemu/assets/30195994/c533a214-8931-44ff-b0ef-19e67065e999)

Removing if statement:
![halo2 2](https://github.com/xemu-project/xemu/assets/30195994/ff5633d5-0cbb-4b05-996c-03f2c2b5c257)

**Comment by polymetal0** [comment]
I made an attempt at fixing this in #1651, among other things. Feel free to test it with any other games where this issue appears 👍

**Comment by C4N1SMAJ0R** [comment]
> I made an attempt at fixing this in #1651, among other things. Feel free to test it with any other games where this issue appears 👍

How I download it for test?
Or this is only for devs?

**Comment by coldhex** [comment]
I've also fixed this here with other Halo 2 fixes: https://github.com/coldhex/xemu/tree/halo2fixes

I think the fundamental issue is that when z_perspective is true, it implies w-buffering and the w-values are not being interpolated with perspective correction. I solved it by writing the perspective correct w-values to gl_FragDepth in the fragment shader.

**Comment by TedMosly** [comment]
Still a problem...  tested both steam deck and PC 

RTX 3070

> I've also fixed this here with other Halo 2 fixes: https://github.com/coldhex/xemu/tree/halo2fixes
> 
> I think the fundamental issue is that when z_perspective is true, it implies w-buffering and the w-values are not being interpolated with perspective correction. I solved it by writing the perspective correct w-values to gl_FragDepth in the fragment shader.

Why there is only source code?
