### ISSUE TITLE
Deadly Skies : Emulator crash when enemy attack you with missile

### ISSUE THREAD

**Issue by GrowlerEA18G** [xemu-project/xemu#964]
### Title

Titles: Deadly Skies (PAL)
https://xemu.app/titles/4b4e0002/#AirForce-Delta-Storm

### Bug Description

Deadly Skies (PAL and JP version of Airforce Delta Storm) still has crash issues when enemy launching at the player. This issue doesnt present in NTSC version of the game 

Steps to reproduce this issue:

Play any mission
Let any enemy fire a missile at you OR wait until the second voiced chatter in the mission plays (happens at around 4 minutes mark on first mission)
The audio then suddenly stops, and the emulator becomes not responding afterwards
OR

Don't press anything at title screen and let the game loads demo reel. The emulator will hang shortly afterwards.

### Expected Behavior

The missile alert beep should play and loops until the missile misses/hits you without freezing the emulator. The voiced dialogue should play without freezing the emulator.

### xemu Version

v0.7.18

**Comment by abaire** [comment]
Is the emulator completely hung, or is the menu still responsive and just the game is hung?

**Comment by GrowlerEA18G** [comment]
> Is the emulator completely hung, or is the menu still responsive and just the game is hung?

the Emulator is completely hung. It's the same issue of this
https://github.com/mborgerson/xemu/issues/361

But the NTSC version of the game (Airforce Delta Storm) is fixed, completely playable , while the PAL version (which is way more superior because it has more planes and better mission design) still has the said issue

**Comment by abaire** [comment]
Can you close this issue since it's an exact duplicate of #361? You can make a comment on that bug indicating that it's still present in 0.7.18 (#361 already states that this only affects PAL and NTSC-J)

**Comment by GrowlerEA18G** [comment]
> Can you close this issue since it's an exact duplicate of #361? You can make a comment on that bug indicating that it's still present in 0.7.18 (#361 already states that this only affects PAL and NTSC-J)


I mean the NTSC version is fixed but it's still an issue in the PAL version so maybe it's still count?

**Comment by abaire** [comment]
> I mean the NTSC version is fixed but it's still an issue in the PAL version so maybe it's still count?

If you read #361 it already says that it affects PAL and NTSC-J, so this bug doesn't add any new information other than the fact that you've tested it with a recent version, which you can add as a comment on #361.
